jobs:
- name: smoketest
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          echo ${SMOKEY}
      params:
        SMOKEY: ((smokey))